## Starting phase

importing everything & performing data cleaning and some other stuff...

In [34]:
import pandas as pd
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import  DataLoader, TensorDataset


%matplotlib inline

In [35]:
data = pd.read_csv("ct_slice_train.csv")
data.head()

,ID,value0,value1,value2,value3,value4,value5,value6,value7,value8,...,value375,value376,value377,value378,value379,value380,value381,value382,value383,TARGET
0,0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.673369,0.000000,-0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.25,56.667181
1,1,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.25,62.455880
2,2,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.561189,0.791667,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.25,57.597645
3,3,0.0,0.0,0.019536,0.0,0.640917,0.875338,0.000000,0.000000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,75.635799
4,4,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.25,54.977994

In [36]:
data.drop(columns=['ID'],inplace=True)

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42800 entries, 0 to 42799
Columns: 385 entries, value0 to TARGET
dtypes: float64(385)
memory usage: 125.7 MB

In [38]:
data.isnull().any(axis=0).sum()

0

In [39]:
data["TARGET"].describe()

count    42800.000000
mean        47.086058
std         22.325819
min          1.738733
25%         30.005851
50%         44.060878
75%         63.752913
max         97.320148
Name: TARGET, dtype: float64

In [40]:
data.shape

(42800, 385)

In [41]:
X = data.drop(columns=["TARGET"])
y = data['TARGET']

X.shape, y.shape

((42800, 384), (42800,))

In [42]:
zero_columns = X.columns[X.var(axis=0) < 0.001]  # ['value59', 'value69', 'value179', 'value189', 'value351']
X = X.drop(columns=zero_columns)
X.shape

(42800, 374)

## Device Agnostic Code

In [43]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## Train & Test split

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, random_state=42)

In [45]:
len(X_train), len(X_val), len(y_train), len(y_val)

(34240, 8560, 34240, 8560)

In [46]:
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_val = scalar.transform(X_val)

In [47]:
scalar_1 = StandardScaler()
y_train = scalar_1.fit_transform(y_train.values.reshape(-1, 1))
y_val = scalar_1.transform(y_val.values.reshape(-1, 1))

In [48]:
print(type(X_train), type(y_train))
print(type(X_val), type(y_val))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>

In [49]:
X_train = torch.tensor(X_train, dtype=torch.float32, device=device)
X_val = torch.tensor(X_val, dtype=torch.float32, device=device)
y_train = torch.tensor(y_train, dtype=torch.float32, device=device)
y_val = torch.tensor(y_val, dtype=torch.float32, device=device)

In [50]:
train_data = DataLoader(TensorDataset(X_train, y_train), batch_size=64, shuffle=True)
val_data = DataLoader(TensorDataset(X_val, y_val), batch_size=64, shuffle=False)
print(f"Total number of batches: 34,240 samples ÷ 64 samples per batch = {len(train_data)}")

Total number of batches: 34,240 samples ÷ 64 samples per batch = 535

## Visualization

In [51]:
def plot_prediction(train_data=X_train,
                    train_labels=y_train,
                    test_data=X_val,
                    test_labels=y_val,
                    predictions=None):
    
    plt.figure(figsize=(10, 7))
    plt.scatter(train_data, train_labels, c='b', s=4, label="Training data")
    plt.scatter(test_data, test_labels, c='g', s=4, label="Testing data")

    if predictions is not None:
        plt.scatter(test_data, predictions, c='r', s=4, label="predictions")

    plt.legend(prop={"size": 14});

In [52]:
len(X_val), len(y_val)

(8560, 8560)

In [53]:
# plot_prediction()

## Model Building

In [54]:
torch.manual_seed(42)

class LinearRegressionModel(nn.Module):
    
    def __init__(self, in_features, hidden_sizes, out_features):
        super().__init__()
        sizes = [in_features] + hidden_sizes
        layers = []
        for i in range(len(sizes)-1):
            layers.append(nn.Linear(sizes[i], sizes[i+1]))
            layers.append(nn.ReLU())
        layers.append(nn.Linear(sizes[-1], out_features))
        self.net = nn.Sequential(*layers)
    
    def forward(self, x):
        return self.net(x)

In [55]:
torch.manual_seed(42)

model = LinearRegressionModel(374, [256, 128, 64], 1)
model, model.state_dict()

(LinearRegressionModel(
   (net): Sequential(
     (0): Linear(in_features=374, out_features=256, bias=True)
     (1): ReLU()
     (2): Linear(in_features=256, out_features=128, bias=True)
     (3): ReLU()
     (4): Linear(in_features=128, out_features=64, bias=True)
     (5): ReLU()
     (6): Linear(in_features=64, out_features=1, bias=True)
   )
 ),
 OrderedDict([('net.0.weight',
               tensor([[ 3.9533e-02,  4.2919e-02, -1.2114e-02,  ...,  2.9832e-02,
                        -3.0107e-02, -6.7122e-03],
                       [-3.8119e-02, -2.4946e-02,  9.3644e-03,  ..., -2.3476e-02,
                         3.6169e-02, -3.5381e-02],
                       [-2.8513e-02,  3.7747e-02,  1.6315e-02,  ...,  1.8254e-02,
                        -2.6432e-02, -4.2253e-02],
                       ...,
                       [ 3.9516e-02,  4.5252e-02,  3.3498e-02,  ...,  3.9001e-02,
                         1.5738e-02,  7.3761e-05],
                       [ 3.0505e-02,  2.4870e-02, -5.2768e-03,  ...,  1.3918e-02,
                         4.9267e-02, -4.9819e-02],
                       [-4.7213e-02, -4.2383e-02, -2.2056e-02,  ..., -9.6800e-03,
                         5.0919e-02, -3.7565e-02]])),
              ('net.0.bias',
               tensor([-4.5949e-02, -3.2813e-02,  1.5424e-02,  5.1228e-02,  1.7956e-02,
                        3.7318e-02,  9.1638e-03, -2.9968e-02,  2.3949e-02,  1.5233e-02,
                       -3.7545e-03, -1.5771e-02, -3.1908e-02,  2.7884e-02, -9.9410e-03,
                        1.9294e-02, -9.9414e-03, -2.4142e-02,  4.9268e-02, -1.2897e-03,
                       -4.4562e-02,  1.7402e-02, -3.3233e-02,  2.2397e-02, -1.3420e-02,
                       -4.9291e-02, -1.4918e-02,  1.0850e-02,  4.6744e-02,  3.9619e-02,
                        7.9399e-03, -4.6747e-02, -5.1635e-02, -3.5891e-02, -3.4692e-02,
                        1.4729e-03,  2.5627e-02, -2.7728e-02, -3.7708e-02,  2.0239e-02,
                       -4.8684e-02, -8.8187e-03,  2.3400e-02, -2.2038e-02,  1.3252e-03,
                       -3.1416e-02, -4.6639e-02, -1.8691e-02,  1.8581e-02, -6.1857e-03,
                       -4.9976e-02, -2.4947e-02, -1.7662e-02, -4.0664e-02, -1.5192e-02,
                       -1.0773e-02, -4.7584e-02, -1.8973e-02,  3.7473e-02, -1.8135e-02,
                       -1.0481e-02, -2.2765e-02,  1.6828e-02,  1.4002e-02,  2.0813e-02,
                        3.9368e-02, -1.6656e-02,  2.3075e-02, -4.4992e-02, -4.3143e-02,
                        2.5441e-02, -1.3751e-02,  1.9624e-02, -2.7413e-02,  1.4982e-02,
                       -3.5051e-04,  1.7328e-02, -2.5033e-02,  1.7947e-02, -4.6808e-02,
                        2.4882e-02,  1.9395e-02,  2.2975e-02, -3.9174e-02,  1.5821e-02,
                       -1.9537e-02, -4.5410e-02, -4.8502e-02,  7.6491e-05, -3.7046e-02,
                        6.8593e-03, -4.8332e-02,  1.4712e-02, -9.7790e-03, -4.6715e-06,
                       -1.5324e-03,  1.6352e-03,  1.3755e-02,  9.5760e-03, -2.6913e-02,
                        2.4010e-02,  9.1325e-03, -1.6484e-02,  8.9562e-03,  4.3513e-02,
                       -2.3817e-03, -2.0262e-02,  4.7885e-02,  9.3951e-03,  1.8249e-02,
                        4.9796e-05, -4.0158e-02,  3.6363e-02, -9.5433e-03,  3.3527e-02,
                        3.9101e-02,  3.2874e-02, -1.2889e-02, -2.6492e-02, -2.0312e-02,
                       -2.3178e-02, -1.9513e-02, -4.5089e-03,  4.8089e-03,  9.8839e-03,
                       -4.5209e-02, -2.0805e-02, -4.9792e-02,  2.1222e-02,  3.3452e-02,
                       -5.0644e-02, -4.7659e-02,  4.9060e-02,  3.9065e-02,  4.7721e-02,
                       -1.8725e-02,  1.7559e-02, -4.5859e-02, -7.5711e-03, -2.0260e-02,
                        1.7786e-02, -3.4146e-02,  1.1721e-02, -1.8139e-02, -3.7408e-02,
                       -2.8121e-02, -2.9366e-02,  6.7257e-03, -3.5018e-02, -3.7287e-02,
                        3.6777e-02, -2.0631e-02,  1.5197e-02,  2.8764e-02, -2.6562e-02,
                        2.7070e-02, -3.6821e-02,  1.2445e-02,  1.9444e-02, -1.7361e-02,
                       -9.7601e-03,  2.9272e-02, -1.5343e-02,  4.0553e-02,  6.8431e-03,
                       -1.6984e-03,  2.8190e-02, -1.6580e-02,  2.2600e-02,  2.8529e-02,
                        2.6461e-02,  4.9663e-02,  1.4921e-02,  4.5457e-04, -4.3630e-02,
                        4.4885e-02,  4.7679e-02,  1.1422e-02, -1.5924e-03, -1.2918e-02,
                       -5.6523e-03, -1.6609e-02,  1.2008e-02,  2.3130e-02,  8.1068e-03,
                       -5.0307e-02, -4.3837e-02, -1.6159e-02,  8.1060e-03, -3.8508e-02,
                       -3.0865e-02, -3.1539e-02, -1.3881e-02, -1.4856e-02,  1.6991e-02,
                        4.7598e-02, -3.8171e-02,  1.5171e-02, -2.7989e-02, -4.6388e-02,
                        3.6700e-02,  3.3947e-02, -4.0017e-02,  1.5888e-02,  4.3789e-03,
                        2.1396e-02,  4.4947e-02,  5.0774e-02, -3.0524e-02,  7.8604e-03,
                        3.2962e-02,  2.9057e-02,  8.9407e-04, -1.0107e-03, -3.1752e-02,
                        3.7788e-02,  3.5203e-02, -4.1631e-02,  5.1262e-02, -1.0459e-02,
                        2.9281e-02,  2.7829e-02,  2.8267e-02,  1.9915e-03, -1.7907e-02,
                        1.1757e-02,  1.8452e-02, -4.7840e-02,  1.4253e-02,  2.6809e-02,
                        1.0902e-04,  1.5774e-02,  2.7460e-02,  4.8922e-02,  2.4672e-02,
                        1.7865e-02, -6.4010e-03, -1.2412e-02,  4.9231e-02,  1.7945e-02,
                        4.0000e-02,  4.6612e-02, -1.3019e-02, -2.1062e-02, -5.1128e-02,
                        2.9455e-02, -3.0341e-04, -9.0497e-04, -1.1264e-02, -1.4329e-02,
                        1.7959e-02, -3.2753e-02, -1.1214e-02,  2.2154e-02, -2.2097e-02,
                       -3.2025e-03])),
              ('net.2.weight',
               tensor([[ 0.0371,  0.0015,  0.0145,  ...,  0.0215,  0.0481, -0.0122],
                       [-0.0063,  0.0459,  0.0316,  ...,  0.0128,  0.0465,  0.0035],
                       [-0.0297, -0.0406,  0.0369,  ..., -0.0455, -0.0296, -0.0360],
                       ...,
                       [-0.0268,  0.0204, -0.0225,  ..., -0.0003, -0.0034, -0.0416],
                       [-0.0143,  0.0413,  0.0183,  ...,  0.0576, -0.0433, -0.0323],
                       [-0.0126,  0.0448, -0.0500,  ...,  0.0311,  0.0444,  0.0121]])),
              ('net.2.bias',
               tensor([-0.0014,  0.0273, -0.0306, -0.0616,  0.0381,  0.0242,  0.0411, -0.0407,
                        0.0407,  0.0598, -0.0374, -0.0060,  0.0032, -0.0060,  0.0586, -0.0393,
                        0.0217, -0.0357, -0.0276, -0.0607,  0.0161, -0.0576,  0.0499,  0.0112,
                       -0.0131, -0.0452,  0.0550, -0.0091,  0.0159, -0.0008,  0.0116,  0.0423,
                        0.0086, -0.0385, -0.0591,  0.0584,  0.0375, -0.0373, -0.0313, -0.0394,
                        0.0516,  0.0550,  0.0168,  0.0195, -0.0282, -0.0217, -0.0463,  0.0330,
                        0.0482, -0.0567, -0.0460,  0.0598,  0.0238, -0.0207, -0.0042,  0.0320,
                        0.0046, -0.0327,  0.0352,  0.0213,  0.0520,  0.0446, -0.0248,  0.0084,
                       -0.0556,  0.0299,  0.0164, -0.0357,  0.0448, -0.0312, -0.0403,  0.0118,
                       -0.0505, -0.0400, -0.0256, -0.0173,  0.0510,  0.0067, -0.0261, -0.0619,
                        0.0389,  0.0390,  0.0207,  0.0150,  0.0531,  0.0187, -0.0053, -0.0192,
                       -0.0617,  0.0606, -0.0242,  0.0557,  0.0117, -0.0249,  0.0017,  0.0189,
                       -0.0315, -0.0362,  0.0377, -0.0044, -0.0175,  0.0440, -0.0405,  0.0125,
                       -0.0432, -0.0288, -0.0466, -0.0600, -0.0256, -0.0109,  0.0113, -0.0212,
                       -0.0474, -0.0098, -0.0576, -0.0251,  0.0226, -0.0412, -0.0598,  0.0516,
                        0.0039, -0.0269,  0.0168,  0.0312,  0.0521,  0.0268, -0.0422, -0.0520])),
              ('net.4.weight',
               tensor([[ 0.0532,  0.0289, -0.0038,  ..., -0.0039,  0.0843, -0.0734],
                       [-0.0215,  0.0783,  0.0577,  ..., -0.0653, -0.0082, -0.0491],
                       [ 0.0703, -0.0483,  0.0587,  ..., -0.0238, -0.0100, -0.0334],
                       ...,
                       [ 0.0513, -0.0591,  0.0082,  ...,  0.0537,  0.0594, -0.0257],
                       [-0.0185, -0.0448, -0.0476,  ...,  0.0313, -0.0728,  0.0823],
                       [-0.0592, -0.0466,  0.0329,  ...,  0.0196,  0.0065, -0.0125]])),
              ('net.4.bias',
               tensor([ 1.7978e-03, -4.0662e-02, -4.6215e-02, -3.1977e-02,  1.3611e-02,
                       -4.3734e-02, -3.0170e-02, -2.4620e-02,  5.2928e-02, -5.0752e-02,
                        4.0915e-02,  4.2283e-02, -1.6069e-03,  5.3649e-04,  4.8676e-04,
                        1.5837e-03,  6.1008e-02, -4.1845e-02, -1.9536e-02,  5.8167e-02,
                       -1.6591e-02, -7.2903e-02, -3.6688e-02,  8.4970e-02,  6.7117e-02,
                        6.1729e-03,  5.0242e-02, -6.6845e-02,  5.5145e-02, -3.5549e-02,
                       -8.5154e-02, -3.8443e-02, -6.6059e-02,  2.7836e-02, -6.5403e-02,
                        5.7189e-02,  7.3385e-02, -5.9845e-02, -5.6731e-02,  1.4726e-02,
                        2.0754e-02, -2.6943e-02, -1.1595e-02, -7.4506e-02, -4.8547e-02,
                        4.2073e-02,  2.4948e-02, -1.7524e-03,  2.3456e-02, -5.9657e-02,
                       -6.6944e-02, -5.0977e-02, -1.5208e-02,  7.6344e-02,  6.9628e-02,
                        4.6390e-03, -5.9239e-02, -3.3604e-02, -3.8711e-02,  5.2889e-02,
                       -2.3984e-03, -3.9814e-02, -7.7859e-05,  4.9517e-02])),
              ('net.6.weight',
               tensor([[ 0.0408, -0.1165, -0.0655, -0.1229,  0.1140, -0.0600,  0.1034,  0.0279,
                        -0.1104,  0.0514,  0.1208, -0.0469, -0.1123, -0.1165, -0.0060,  0.0226,
                         0.0068, -0.0832,  0.0520, -0.0369,  0.1121,  0.1006, -0.0713, -0.0407,
                        -0.0879, -0.0424, -0.0672, -0.0810,  0.0600,  0.0887, -0.1118, -0.0787,
                         0.0482,  0.1116,  0.0506,  0.0826,  0.0044, -0.0597, -0.0602, -0.0829,
                        -0.1038,  0.0457, -0.0827, -0.1178,  0.0293,  0.0039,  0.0024, -0.0131,
                        -0.0219, -0.0451, -0.0163,  0.0704, -0.0733,  0.0119, -0.0614, -0.0941,
                         0.0360, -0.0647,  0.1225, -0.1155, -0.1196, -0.1147, -0.0964, -0.0802]])),
              ('net.6.bias', tensor([0.0517]))]))

In [56]:
next(model.parameters()).device

device(type='cpu')

In [57]:
model.to(device)
next(model.parameters()).device

device(type='cpu')

## Training

In [58]:
Loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(params=model.parameters(),
                            lr=0.001)

In [ ]:
torch.manual_seed(42)

epochs = 1000
TRAINING_LOSS = []
VALIDATION_LOSS = []

for epoch in range(epochs):

    model.train()
    for x_batch, y_batch in train_data:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        
        y_pred = model(x_batch)
        loss = Loss_fn(y_pred, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    TRAINING_LOSS.append(loss.item())

    # Testing
    model.eval()
    with torch.inference_mode():
        for x_batch, y_batch in val_data:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)
            
            test_pred = model(x_batch)
            test_loss = Loss_fn(test_pred, y_batch)
            VALIDATION_LOSS.append(test_loss.item())

    # print out what's happening
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss} | Test loss: {test_loss}")

Epoch: 0 | Loss: 0.7609257102012634 | Test loss: 0.7439139485359192
Epoch: 10 | Loss: 0.051403775811195374 | Test loss: 0.04697291553020477
Epoch: 20 | Loss: 0.029665054753422737 | Test loss: 0.02605157159268856
Epoch: 30 | Loss: 0.02883528545498848 | Test loss: 0.018816063180565834
Epoch: 40 | Loss: 0.01137616392225027 | Test loss: 0.01540455687791109
Epoch: 50 | Loss: 0.015323775820434093 | Test loss: 0.013431932777166367
Epoch: 60 | Loss: 0.018219927325844765 | Test loss: 0.01223013922572136
Epoch: 70 | Loss: 0.011575683951377869 | Test loss: 0.011605157516896725
Epoch: 80 | Loss: 0.008426729589700699 | Test loss: 0.010861378163099289
Epoch: 90 | Loss: 0.019311828538775444 | Test loss: 0.010334734804928303
Epoch: 100 | Loss: 0.011035997420549393 | Test loss: 0.009837389923632145
Epoch: 110 | Loss: 0.010545746423304081 | Test loss: 0.009282625280320644
Epoch: 120 | Loss: 0.009082687087357044 | Test loss: 0.009067974053323269
Epoch: 130 | Loss: 0.006463498342782259 | Test loss: 0.008611232973635197
Epoch: 140 | Loss: 0.004293321631848812 | Test loss: 0.00833887979388237
Epoch: 150 | Loss: 0.002708122134208679 | Test loss: 0.007796529680490494
Epoch: 160 | Loss: 0.005371129605919123 | Test loss: 0.007651910185813904
Epoch: 170 | Loss: 0.0053720539435744286 | Test loss: 0.007505381945520639
Epoch: 180 | Loss: 0.004426422528922558 | Test loss: 0.007316535338759422
Epoch: 190 | Loss: 0.003886195132508874 | Test loss: 0.0070723737590014935
Epoch: 200 | Loss: 0.00416097417473793 | Test loss: 0.006791232619434595
Epoch: 210 | Loss: 0.004092950373888016 | Test loss: 0.0066271573305130005
Epoch: 220 | Loss: 0.0033201263286173344 | Test loss: 0.006392901297658682
Epoch: 230 | Loss: 0.003236191812902689 | Test loss: 0.0062684714794158936
Epoch: 240 | Loss: 0.0042016515508294106 | Test loss: 0.006202476564794779
Epoch: 250 | Loss: 0.0033531684894114733 | Test loss: 0.005978669971227646
Epoch: 260 | Loss: 0.0028208037838339806 | Test loss: 0.005906958132982254
Epoch: 270 | Loss: 0.0030930524226278067 | Test loss: 0.005811937619000673
Epoch: 280 | Loss: 0.0031451364047825336 | Test loss: 0.0056052920408546925
Epoch: 290 | Loss: 0.003374988678842783 | Test loss: 0.005546215455979109
Epoch: 300 | Loss: 0.0029126224108040333 | Test loss: 0.005369177088141441
Epoch: 310 | Loss: 0.002180452924221754 | Test loss: 0.005315747577697039
Epoch: 320 | Loss: 0.0024539080914109945 | Test loss: 0.005268152337521315
Epoch: 330 | Loss: 0.002566675888374448 | Test loss: 0.005178437102586031
Epoch: 340 | Loss: 0.0021946921478956938 | Test loss: 0.005050364416092634
Epoch: 350 | Loss: 0.004232840612530708 | Test loss: 0.0049510919488966465
Epoch: 360 | Loss: 0.0037917993031442165 | Test loss: 0.004928626585751772
Epoch: 370 | Loss: 0.0014746839879080653 | Test loss: 0.0049317278899252415
Epoch: 380 | Loss: 0.0021911850199103355 | Test loss: 0.00477595953270793
Epoch: 390 | Loss: 0.0021280855871737003 | Test loss: 0.0047423820942640305
Epoch: 400 | Loss: 0.0024011211935430765 | Test loss: 0.004652154631912708
Epoch: 410 | Loss: 0.0017436204943805933 | Test loss: 0.004652093630284071
Epoch: 420 | Loss: 0.0021326574496924877 | Test loss: 0.004639110527932644
Epoch: 430 | Loss: 0.0032549554016441107 | Test loss: 0.004579726606607437
Epoch: 440 | Loss: 0.001982147805392742 | Test loss: 0.004468376282602549
Epoch: 450 | Loss: 0.002118073869496584 | Test loss: 0.0044237649999558926
Epoch: 460 | Loss: 0.0018891030922532082 | Test loss: 0.004465390462428331
Epoch: 470 | Loss: 0.0034370808862149715 | Test loss: 0.004379634279757738
Epoch: 480 | Loss: 0.0014601165894418955 | Test loss: 0.004352082964032888
Epoch: 490 | Loss: 0.001900533214211464 | Test loss: 0.004352811258286238
Epoch: 500 | Loss: 0.0015390780754387379 | Test loss: 0.004304989241063595
Epoch: 510 | Loss: 0.0018198436591774225 | Test loss: 0.004294804763048887
Epoch: 520 | Loss: 0.0016488274559378624 | Test loss: 0.004285406321287155
Epoch: 530 | Loss: 0.0019462655764073133 | Test loss: 0.0041948226280510426
Epoch: 540 | Loss: 0.0012708829017356038 | Test loss: 0.004213001579046249
Epoch: 550 | Loss: 0.0016668771859258413 | Test loss: 0.004150847438722849
Epoch: 560 | Loss: 0.0008716928423382342 | Test loss: 0.0041588954627513885
Epoch: 570 | Loss: 0.0013114477042108774 | Test loss: 0.004104763735085726
Epoch: 580 | Loss: 0.0010642866836860776 | Test loss: 0.0041085053235292435
Epoch: 590 | Loss: 0.0014524688012897968 | Test loss: 0.004077686462551355
Epoch: 600 | Loss: 0.0016808346845209599 | Test loss: 0.004010852891951799
Epoch: 610 | Loss: 0.0016746296314522624 | Test loss: 0.004022579174488783
Epoch: 620 | Loss: 0.0010521489894017577 | Test loss: 0.003995426464825869
Epoch: 630 | Loss: 0.0010567659046500921 | Test loss: 0.003948623780161142
Epoch: 640 | Loss: 0.00147440645378083 | Test loss: 0.003948025405406952
Epoch: 650 | Loss: 0.0012804318685084581 | Test loss: 0.0039212023839354515
Epoch: 660 | Loss: 0.0013734882231801748 | Test loss: 0.0038811180274933577
Epoch: 670 | Loss: 0.0018679527565836906 | Test loss: 0.0038889069110155106
Epoch: 680 | Loss: 0.0008860922534950078 | Test loss: 0.003863350488245487
Epoch: 690 | Loss: 0.0013559104409068823 | Test loss: 0.003811867907643318
Epoch: 700 | Loss: 0.0014572377549484372 | Test loss: 0.0038343816995620728
Epoch: 710 | Loss: 0.0007733349339105189 | Test loss: 0.003829282708466053
Epoch: 720 | Loss: 0.001876374939456582 | Test loss: 0.003806621767580509
Epoch: 730 | Loss: 0.0006149403052404523 | Test loss: 0.003765330882743001
Epoch: 740 | Loss: 0.0008517404785379767 | Test loss: 0.00371535518206656
Epoch: 750 | Loss: 0.0011917126830667257 | Test loss: 0.003731027478352189
Epoch: 760 | Loss: 0.0009537715231999755 | Test loss: 0.0037338193506002426
Epoch: 770 | Loss: 0.0011707466328516603 | Test loss: 0.003711715340614319
Epoch: 780 | Loss: 0.0012003269512206316 | Test loss: 0.0036762868985533714
Epoch: 790 | Loss: 0.0010254005901515484 | Test loss: 0.003676525317132473
Epoch: 800 | Loss: 0.0012174573494121432 | Test loss: 0.0036366786807775497
Epoch: 810 | Loss: 0.0012649291893467307 | Test loss: 0.003648995654657483
Epoch: 820 | Loss: 0.0006787679740227759 | Test loss: 0.003624403616413474
Epoch: 830 | Loss: 0.0008527064928784966 | Test loss: 0.0036098146811127663
Epoch: 840 | Loss: 0.0016209289897233248 | Test loss: 0.003586724167689681
Epoch: 850 | Loss: 0.0006351794581860304 | Test loss: 0.0035556780640035868
Epoch: 860 | Loss: 0.0016658187378197908 | Test loss: 0.0035492100287228823
Epoch: 870 | Loss: 0.0011005036067217588 | Test loss: 0.0035616960376501083
Epoch: 880 | Loss: 0.001067700213752687 | Test loss: 0.0035239241551607847
Epoch: 890 | Loss: 0.0010874636936932802 | Test loss: 0.0035100597888231277
Epoch: 900 | Loss: 0.0015633234288543463 | Test loss: 0.0034859005827456713
Epoch: 910 | Loss: 0.0008571985526941717 | Test loss: 0.0035168484319001436
Epoch: 920 | Loss: 0.0013545671245083213 | Test loss: 0.0034861022140830755
Epoch: 930 | Loss: 0.0007241631974466145 | Test loss: 0.0034886449575424194
Epoch: 940 | Loss: 0.0006509332451969385 | Test loss: 0.003461959073320031
Epoch: 950 | Loss: 0.0008263549534603953 | Test loss: 0.0034467915538698435
Epoch: 960 | Loss: 0.0007692425278946757 | Test loss: 0.0034428101498633623
Epoch: 970 | Loss: 0.000828917371109128 | Test loss: 0.0034127896651625633
Epoch: 980 | Loss: 0.001377559034153819 | Test loss: 0.003419424407184124

KeyboardInterrupt:

## Testing upon external data

In [103]:
ext_test_data = pd.read_csv("ct_slice_test_noLabels.csv")
print(ext_test_data.shape)

(10700, 385)

In [104]:
ext_test_data.head(2)

,ID,value0,value1,value2,value3,value4,value5,value6,value7,value8,...,value374,value375,value376,value377,value378,value379,value380,value381,value382,value383
0,42800,0.0,0.0,0.0,0.0,0.0,0.000000,0.909039,0.0,-0.25,...,0.0,0.0,0.0,0.00000,0.0000,0.000000,0.865903,0.343742,0.0,-0.25
1,42801,0.0,0.0,0.0,0.0,0.0,0.793039,0.000000,0.0,0.00,...,0.0,0.0,0.0,0.99694,0.9998,0.999976,0.998890,0.000000,0.0,-0.25

In [105]:
id_col = ext_test_data["ID"] # Taking it for submission

In [106]:
X1 = ext_test_data.drop(["ID"], axis=1)
X1.head(2)

,value0,value1,value2,value3,value4,value5,value6,value7,value8,value9,...,value374,value375,value376,value377,value378,value379,value380,value381,value382,value383
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.909039,0.0,-0.25,-0.25,...,0.0,0.0,0.0,0.00000,0.0000,0.000000,0.865903,0.343742,0.0,-0.25
1,0.0,0.0,0.0,0.0,0.0,0.793039,0.000000,0.0,0.00,-0.25,...,0.0,0.0,0.0,0.99694,0.9998,0.999976,0.998890,0.000000,0.0,-0.25

In [107]:
col = X1.columns[X1.var(axis=0) < 0.001]
print(len(col))
X1 = X1.drop(columns=col)
X1.shape

10

(10700, 374)

In [108]:
X1 = scalar.transform(X1)

In [109]:
X1_tensor = torch.tensor(X1, dtype=torch.float32, device=device)

In [110]:
model.eval()
with torch.inference_mode():
    predictions = model(X1_tensor)

In [111]:
predictions.shape

torch.Size([10700, 1])

In [112]:
predictions

tensor([[ 0.1561],
        [-0.3481],
        [ 1.1302],
        ...,
        [-0.8324],
        [-1.2770],
        [ 0.0337]])

In [114]:
predictions.cpu().numpy()
scalar.inverse_transform(predictions)
predictions

ValueError: non-broadcastable output operand with shape (10700,1) doesn't match the broadcast shape (10700,374)